### PR TITLE
Update about.html

### PR DESCRIPTION
**Pull request by hzxie**
Fix missing `</section>` tag.

### CODE REVIEW

**Comment by Epsilon-Lee** [comment]
WTF!

2017-03-11 15:46 GMT+08:00 Haozhe Xie <notifications@github.com>:

**Comment by hzxie** [comment]
Please merge this PR in GitHub.

**Comment by Epsilon-Lee** [comment]
Are you robot?

2017-03-12 18:03 GMT+08:00 Haozhe Xie <notifications@github.com>:

**Comment by hzxie** [comment]
@Epsilon-Lee 
It seems that I'm too slow to reply this message.

**Comment by Epsilon-Lee** [comment]
I don't know how to reconcile your pull request? Can you tell me the
solution.

2017-03-12 19:11 GMT+08:00 Haozhe Xie <notifications@github.com>:

**Comment by hzxie** [comment]
Visit this [page](https://github.com/Epsilon-Lee/epsilon-lee.github.io/pull/1#issuecomment-285941853) with your browser. Then you will see a button like "Merge" or something similar to it.

**Comment by hzxie** [comment]
See also: https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

**Comment by Epsilon-Lee** [comment]
http://ieeexplore.ieee.org/xpl/abstractToc.jsp?arnumber=7555397
这本书哈，麻烦啦，下载了用gmail发给我就行。

2017-03-13 19:05 GMT+08:00 Haozhe Xie <notifications@github.com>:

**Pull request closed without merging**
